DISTNAME		=	sysview-${V}
V				=	0.0.0
COMMENT			=	html views for sysreport.
CATEGORIES		=	sysutils

MAINTAINER		=	Michael Wilson <mw@1wilson.org>
HOMEPAGE 		=	https://github.com/torarg/sysview

# BSD
PERMIT_PACKAGE	=	Yes

SITES			=	https://github.com/torarg/sysview/archive/refs/tags/
DISTFILES		=	sysreport-{}${V}${EXTRACT_SUFX}

.include <bsd.port.mk>
